"""Rename pitch in Dislikes to pitch_id

Revision ID: bc519f04a43b
Revises: ece24b71b1b3
Create Date: 2022-05-14 05:34:51.771681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc519f04a43b'
down_revision = 'ece24b71b1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislike', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('dislike_pitch_fkey', 'dislike', type_='foreignkey')
    op.create_foreign_key(None, 'dislike', 'pitch', ['pitch_id'], ['id'])
    op.drop_column('dislike', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislike', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.create_foreign_key('dislike_pitch_fkey', 'dislike', 'pitch', ['pitch'], ['id'])
    op.drop_column('dislike', 'pitch_id')
    # ### end Alembic commands ###
