"""Add profile_pic_path to User model

Revision ID: e438af20325d
Revises: 5fcfa17b22bf
Create Date: 2022-05-14 15:35:30.953342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e438af20325d'
down_revision = '5fcfa17b22bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile_pic_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profile_pic_path')
    # ### end Alembic commands ###
