"""Add Like and dislike models

Revision ID: ece24b71b1b3
Revises: ec913799d281
Create Date: 2022-05-14 05:14:21.278033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece24b71b1b3'
down_revision = 'ec913799d281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('like_pitch_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'pitch', ['pitch_id'], ['id'])
    op.drop_column('like', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_pitch_fkey', 'like', 'pitch', ['pitch'], ['id'])
    op.drop_column('like', 'pitch_id')
    # ### end Alembic commands ###
